### PR TITLE
Use custom separator for service name and namespace

### LINKED ISSUE #378: A hyphenated namespace causes wrong DNS results
Hi there!
Please take a look at what I got for k8s services hosted in a hyphenated namespace.

```
kubectl get pods -n dev-sherba
NAME                             READY   STATUS    RESTARTS   AGE
grpc-client-5d6549c4c6-gdgd2     1/1     Running   1          108m
grpc-server-676f69498b-556zx     1/1     Running   0          152m
grpc-server-676f69498b-b82gl     1/1     Running   0          152m
grpc-server-676f69498b-cv7v8     1/1     Running   0          152m
tiller-deploy-68666bd84b-dvdtd   1/1     Running   0          7h16m

kubectl get svc -n dev-sherba
NAME                TYPE           CLUSTER-IP   EXTERNAL-IP                                     PORT(S)              AGE
grpc-server         ClusterIP      None         <none>                                          5300/TCP             153m

kubectl get svc -n maesh
NAME                                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)              AGE
maesh-grpc-server-dev-sherba         ClusterIP   10.0.60.143    <none>        5300/TCP             20m



kubectl exec -it -n dev-sherba grpc-client-5d6549c4c6-gdgd2 -- /bin/bash

root@grpc-client-5d6549c4c6-gdgd2:/# nslookup grpc-server.dev-sherba      
Server:		10.0.0.3
Address:	10.0.0.3#53

Name:	grpc-server.dev-sherba.svc.cluster.local
Address: 10.100.94.28
Name:	grpc-server.dev-sherba.svc.cluster.local
Address: 10.100.7.3
Name:	grpc-server.dev-sherba.svc.cluster.local
Address: 10.100.197.153



root@grpc-client-5d6549c4c6-gdgd2:/# nslookup grpc-server.dev-sherba.maesh
Server:		10.0.0.3
Address:	10.0.0.3#53

Name:	grpc-server-dev.sherba.maesh
Address: 10.0.60.143
```

### PR DESCRIPTION
**Pull request by dtomcej**
This PR:

- Uses a custom separator `-shadow-service-` instead of `-` to separate name and namespace
- Adds integration tests to ensure dashes in names and namespaces work

Fixes #378

### CODE REVIEW

**Comment by valerauko** [comment]
How does this behave if the service/namespace name includes "shadow-service"?

**Comment by dtomcej** [comment]
>How does this behave if the service/namespace name includes "shadow-service"?

If the service ends in `shadow-service`, and or ends in `shadow`, and the namespace starts with `service-` then the issue will present itself.

Another solution we toyed with was to use a random string like `SDysdSDT` to ensure there would be no overlap, but it is not a very clean looking solution, and could possibly interfere with automated systems and debugging. At least with a clean string, reproducing would be easy.

**Comment by valerauko** [comment]
I feel that there's a pretty good chance of services being named "shadow-service" in the wild. A phrase like "maesh-shadowed" would maybe be less likely to collide? Just an idea.

**Comment by dtomcej** [comment]
Using a single word as the separator would reduce the risk of a match...

Perhaps a word like `pineapple` or something

**Comment by SantoDE** [comment]
Maybe we should just `maesh` ? :) @valerauko @dtomcej

**Comment by dtomcej** [comment]
I have an idea for a separator string.

**Comment by dtomcej** [comment]
There were a variety of options to go with, but:

`bWFlc2g` is `maesh` in base64.

**Comment by SantoDE** [comment]
I like that one @dtomcej

**Pull request merged**
